### ISSUE TITLE
java.lang.RuntimeException: Could not read input channel file descriptors from parcel.

### ISSUE THREAD

**Issue by devgianlu** [devgianlu/Aria2App#13]
```
 java.lang.RuntimeException: Could not read input channel file descriptors from parcel.
       at android.view.InputChannel.nativeReadFromParcel(InputChannel.java)
       at android.view.InputChannel.readFromParcel(InputChannel.java:148)
       at android.view.InputChannel$1.createFromParcel(InputChannel.java:39)
       at android.view.InputChannel$1.createFromParcel(InputChannel.java:37)
       at com.android.internal.view.InputBindResult.(InputBindResult.java:68)
       at com.android.internal.view.InputBindResult$1.createFromParcel(InputBindResult.java:112)
       at com.android.internal.view.InputBindResult$1.createFromParcel(InputBindResult.java:110)
       at com.android.internal.view.IInputMethodManager$Stub$Proxy.startInputOrWindowGainedFocus(IInputMethodManager.java:723)
       at android.view.inputmethod.InputMethodManager.startInputInner(InputMethodManager.java:1295)
       at android.view.inputmethod.InputMethodManager.onPostWindowFocus(InputMethodManager.java:1538)
       at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3934)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6602)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:453)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:821)
```

This is probably caused by a lack of file descriptors which are being consumed by the HttpClient.

We should:
- [x] enforce logging to see if this issue happens with HTTP connection method
- [ ] go away from OkHttp and write a much efficient implementation that suits our usecase

**Comment by devgianlu** [comment]
This ended up being a minor issue.

**Comment by premacck** [comment]
@devgianlu Did this issue happen with the HTTP connection method for you?

**Comment by devgianlu** [comment]
Yeah, it's because a lot of connections are opened for polling.

**Comment by premacck** [comment]
So how did you manage to fix that? did you open the connection sequentially?

**Comment by devgianlu** [comment]
You should be able to fix this by having connection keep alive available on the server.

**Comment by premacck** [comment]
Alright thanks!
