### ISSUE TITLE
java.lang.SecurityException: Unable to start service: foreground not allowed as per app op

### ISSUE THREAD

**Issue by devgianlu** [devgianlu/Aria2App#36]
```
java.lang.SecurityException: Unable to start service Intent { act=com.gianlu.aria2app.Services.NotificationService.START cmp=com.gianlu.aria2app/.Services.NotificationService (has extras) }: foreground not allowed as per app op
       at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1574)
       at android.app.ContextImpl.startForegroundService(ContextImpl.java:1538)
       at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:669)
       at androidx.core.content.ContextCompat.startForegroundService(ContextCompat.java:675)
       at com.gianlu.aria2app.Services.NotificationService.startInternal(NotificationService.java:110)
       at com.gianlu.aria2app.Services.NotificationService.start(NotificationService.java:118)
       at com.gianlu.aria2app.ThisApplication.onCreate(ThisApplication.java:61)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5920)
       at android.app.ActivityThread.access$1100(ActivityThread.java:200)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6718)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

Happens on HTC Android 9.

**Comment by devgianlu** [comment]
Catching the exception.
