### ISSUE TITLE
OutOfMemoryError when using WebSockets

### ISSUE THREAD

**Issue by devgianlu** [devgianlu/Aria2App#43]
```
Fatal Exception: java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Out of memory
       at java.lang.Thread.nativeCreate(Thread.java)
       at java.lang.Thread.start(Thread.java:753)
       at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:970)
       at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1388)
       at okhttp3.RealCall$AsyncCall.executeOn(RealCall.java:182)
       at okhttp3.Dispatcher.promoteAndExecute(Dispatcher.java:186)
       at okhttp3.Dispatcher.enqueue(Dispatcher.java:137)
       at okhttp3.RealCall.enqueue(RealCall.java:126)
       at okhttp3.internal.ws.RealWebSocket.connect(RealWebSocket.java:193)
       at okhttp3.OkHttpClient.newWebSocket(OkHttpClient.java:435)
       at com.gianlu.aria2app.NetIO.WebSocketClient.(WebSocketClient.java:36)
       at com.gianlu.aria2app.NetIO.WebSocketClient.(WebSocketClient.java:42)
       at com.gianlu.aria2app.NetIO.WebSocketClient.checkConnection(WebSocketClient.java:58)
       at ....
```

It is also noticeable that a lot of new threads are created along with a lot of `WebSocketClient`. I wonder why this happens.

**Comment by devgianlu** [comment]
Should be fixed in latest release.
