### ISSUE TITLE
Attempt to invoke virtual method 'int android.text.Layout.getLineForOffset(int)' on a null object reference

### ISSUE THREAD

**Issue by devgianlu** [devgianlu/Aria2App#9]
```
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.text.Layout.getLineForOffset(int)' on a null object reference
       at android.widget.Editor.updateCursorPositionMz(Editor.java:7810)
       at android.widget.Editor.updateCursorsPositions(Editor.java:1963)
       at android.widget.TextView.getUpdatedHighlightPath(TextView.java:5777)
       at android.widget.TextView.onDraw(TextView.java:5963)
       at android.view.View.draw(View.java:17207)
       at android.view.View.updateDisplayListIfDirty(View.java:16185)
       at android.view.View.draw(View.java:16969)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
       at android.view.View.updateDisplayListIfDirty(View.java:16180)
       at android.view.View.draw(View.java:16969)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
       at android.view.View.draw(View.java:17210)
       at com.google.android.material.textfield.TextInputLayout.draw(TextInputLayout.java:1577)
       at android.view.View.updateDisplayListIfDirty(View.java:16185)
       at android.view.View.draw(View.java:16969)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
       at android.view.View.updateDisplayListIfDirty(View.java:16180)
       at android.view.View.draw(View.java:16969)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
       at android.view.View.draw(View.java:17210)
       at android.view.View.updateDisplayListIfDirty(View.java:16185)
       at android.view.View.draw(View.java:16969)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
       at android.view.View.updateDisplayListIfDirty(View.java:16180)
       at android.view.View.draw(View.java:16969)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
       at android.view.View.updateDisplayListIfDirty(View.java:16180)
       at android.view.View.draw(View.java:16969)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
       at android.view.View.updateDisplayListIfDirty(View.java:16180)
       at android.view.View.draw(View.java:16969)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
       at android.view.View.updateDisplayListIfDirty(View.java:16180)
       at android.view.View.draw(View.java:16969)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
       at android.view.View.updateDisplayListIfDirty(View.java:16180)
       at android.view.View.draw(View.java:16969)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
       at android.view.View.draw(View.java:17210)
       at com.android.internal.policy.DecorView.draw(DecorView.java:781)
       at android.view.View.updateDisplayListIfDirty(View.java:16185)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:656)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:662)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:770)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:2867)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2669)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2270)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1300)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6481)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:885)
       at android.view.Choreographer.doCallbacks(Choreographer.java:697)
       at android.view.Choreographer.doFrame(Choreographer.java:633)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:871)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6337)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)
```

**Comment by devgianlu** [comment]
https://stackoverflow.com/questions/51891415/nullpointerexception-on-meizu-devices-in-editor-updatecursorpositionmz/52874217

https://issuetracker.google.com/issues/110741548
